In [1]:
x=int(input('Enter the number: '))
exp=x**3+2*x**2+3*x+4
print(exp)

Enter the number:  5

194

In [2]:
import math
r=float(input("Enter the radius: "))
area=math.pi*r*r
volume=4*math.pi*r*r*r/3
print("Area: ",area)
print('Volume: ',volume)

Enter the radius:  5

Area:  78.53981633974483
Volume:  523.5987755982989

In [3]:
a=1.21
b=1.20
c=1.22
check=(a<b) or (not(c==b)) and (c<a)
print (check)

False

In [4]:
n=int(input("Enter the time: "))
p=1000
r=0.12
a=p*(1+r)**n
print("The amount is",a)

Enter the time:  5

The amount is 1762.3416832000007

In [5]:
import math
a=math.pow(math.e,math.pi)
b=math.pow(math.pi,math.e)
if a>b:
    print("Ok")
else:
    print("Ok Anyway")

Ok

In [6]:
a=-7*20+8/16*2+54
b=7**2//9%3
c=(7-4*2)*10-25*8//5
d=5%10+10-25*8//5
print(a,b,c,d)

-85.0 2 -50 -25

In [7]:
cost_meal=float(input("Enter the cost of the meal: "))
tip=0.18*cost_meal
tax=0.05*cost_meal
grand_total=cost_meal+tax+tip
print(f"The cost was: {cost_meal:.2f}")
print(f"The tax was: {tax:.2f}")
print(f"The tip was: {tip:.2f}")
print(f"The Grand Total was: {grand_total:.2f}")

Enter the cost of the meal:  546

The cost was: 546.00
The tax was: 27.30
The tip was: 98.28
The Grand Total was: 671.58

In [8]:
a=int(input("Enter num1: "))
b=int(input("Enter num2: "))
print("The sum is: ",(a+b))
print("The difference is: ",(a-b))
print("The product is: ",(a*b))
print("The quotient is: ",(a/b))
print("The remainder is: ",(a%b))
print("The Log Result: ",(math.log10(5)))
print("The result is: ",a+b)

Enter num1:  5
Enter num2:  7

The sum is:  12
The difference is:  -2
The product is:  35
The quotient is:  0.7142857142857143
The remainder is:  5
The Log Result:  0.6989700043360189
The result is:  12

In [9]:
d=float(input("Enter the height: "))
vi,a=0,9.8
vf=math.sqrt(math.pow(vi,2)+(2*a*d))
print("The final velocity is: ",vf)

Enter the height:  45

The final velocity is:  29.698484809834998

In [10]:
cel=float(input("Enter degree cel: "))
fah=(cel*9/5)+32
kel=cel++273.15
print(f"Temp in Fahrenheit: {fah:.2f}F")
print(f"Temp in Kelvin: {fah:.2f}K")

Enter degree cel:  45

Temp in Fahrenheit: 113.00F
Temp in Kelvin: 113.00K

In [11]:
num=int(input("Enter a 4 digit integer: "))
dig1=num//1000
dig2=(num//100)%10
dig3=(num//10)%10
dig4=num%10
sum1=dig1+dig2+dig3+dig4
print("The sum is: ",sum1)

Enter a 4 digit integer:  4561

The sum is:  16

In [12]:
num1=int(input())
num2=int(input())
num3=int(input())
min1=min(num1,num2,num3)
max1=max(num1,num2,num3)
mid1=(num1+num2+num3)-min1-max1
print(min1,max1,mid1)

 1
 2
 3

1 3 2

In [13]:
days=int(input("Enter Days: "))
hour=int(input("Enter Hours: "))
minutes=int(input("Enter Minutes: "))
seconds=int(input("Enter Seconds: "))
total=days*24*60*60+hour*60*60+minutes*60+seconds
print(total," Value")

Enter Days:  456
Enter Hours:  5
Enter Minutes:  7
Enter Seconds:  5

39416825  Value

In [14]:
answer=input("Is it raining?: ")
if answer=="Yes":
    print("Carry an umbrella")
else:
    print("Bye")

Is it raining?:  Yes

Carry an umbrella

In [15]:
# try:
#     answer = input("Is it raining?: ")
#     match answer:
#         case "Yes":
#             print("Carry an umbrella.")
#         case "No":
#             print("Bye")
#         case _:
#             print("Don't carry anything")
# except ValueError:
#     print("Error Input")

In [16]:
answer=input("Is it raining?: ")
if answer=="Yes":
    print("Carry an umbrella")
elif answer=="No":
    print("Bye")
else:
    print("Don't carry anything")

Is it raining?:  Yes

Carry an umbrella

In [17]:
marks=int(input("Enter the marks: "))
if marks>=90 and marks<=100:
    print("Excellent: A")
elif marks>=80 and marks<90:
    print("Good: B")
elif marks>=70 and marks<80:
    print("Average: C")
elif marks>=60 and marks<70:
    print("Needs Imporovement: D")
else:
    print("Failing: F")

Enter the marks:  85

Good: B

In [19]:
side1=int(input("Enter the side1: "))
side2=int(input("Enter the side2: "))
side3=int(input("Enter the side3: "))
if side1==side2==side3:
    print("Equilateral Triangle")
elif side1==side2 or side2==side3 or side==side3:
    print("Isosceles Triangle")
else:
    print("Scalene Triangle")

Enter the side1:  4
Enter the side2:  4
Enter the side3:  5

Isosceles Triangle

In [20]:
if int(input("Enter a number: "))%2==0:
    print("The number is even")
else:
    print("The number is odd")

Enter a number:  5

The number is odd

In [21]:
year=int(input("Enter the year: "))
if year%100==0 or year%4==0:
    print("The year is leap")
else:
    print("It's not a leap year")

Enter the year:  2020

The year is leap

In [22]:
prime=int(input('Enter a number: '))
def primes(prime):
    if prime<=1:
        return False
    for i in range(2,math.sqrt(prime)+1):
        if prime%i==0:
            return False
        else:
            return True
print()

Enter a number:  25

### Lab-25/11/2025

In [23]:
colors={'red','orange','yellow','green','red','blue'}
colors

{'blue', 'green', 'orange', 'red', 'yellow'}

In [24]:
len(colors)

5

In [25]:
'red' in colors

True

In [26]:
'purple' in colors

False

In [27]:
'purple' not in colors

True

In [28]:
for color in colors:
    print(color.upper(),end=' ')

GREEN BLUE ORANGE YELLOW RED

In [29]:
numbers=list(range(10))+list(range(5))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]

In [30]:
set(numbers)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [31]:
set()

set()

In [32]:
text='to be or not be that id the question'
unique_words=set(text.split())
for word in sorted(unique_words):
    print(word,end=" ")

be id not or question that the to

In [33]:
{1,3,5}=={3,5,1}

True

In [34]:
{1,3,5}!={3,5,1}

False

In [35]:
{1,3,5}<{3,5,1}

False

In [36]:
{1,3,5}<{7,3,5,1}

True

In [37]:
{1,3,5}<={3,5,1}

True

In [38]:
{1,3}<={3,5,1}

True

In [39]:
{1,3,5}.issubset({3,5,1})

True

In [40]:
{1,3,5}.issubset({3,5,1})

True

In [41]:
{1,3,5}>{3,5,1}

False

In [42]:
{1,3,5,7}>{3,5,1}

True

In [43]:
students={}
name=input("Enter student name: ")
marks=int(input("Enter marks: "))
students[name]=marks
search=input("Enter name to display marks: ")
print(students.get(search,"Student not found"))

Enter student name:  Amulya
Enter marks:  85
Enter name to display marks:  Amulya

85

In [44]:
data={}
for i in range(3):
    name=input("Enter name: ")
    percent=float(input("Enter percentage: "))
    data[name]=percent
print(data)

Enter name:  Amulya
Enter percentage:  85
Enter name:  Deep
Enter percentage:  75
Enter name:  Shri
Enter percentage:  65

{'Amulya': 85.0, 'Deep': 75.0, 'Shri': 65.0}

In [45]:
d=eval(input("Enter dictionary: "))
print(sum(d.values()))

Enter dictionary:  {'A':20,'B':30}

50

In [46]:
e2f={"dog":"chien","cat":"chat","walrus":"morse"}
print(e2f)

{'dog': 'chien', 'cat': 'chat', 'walrus': 'morse'}

In [47]:
tlds={"Canada":"ca","United States":"us","Mexico":"mx"}
a="Canada" in tlds
b="France" in tlds
pairs=[(k,v) for k,v in tlds.items()]
tlds["Sweden"]="sw"
tlds["Sweden"]="se"
rev={v:k for k,v in tlds.items()}

In [48]:
roman = {"I":1,"II":2,"III":3,"V":5}
keys=list(roman.keys())
values=list(roman.values())
items=list(roman.items())

In [49]:
cubes={x:x**3 for x in range(1, 6)}

In [50]:
life = {"animals":{"cats": ["Henri", "Grumpy", "Lucy"],"octopi":{},"emus":{}},"plants":{},"other":{}}

In [51]:
s="mississippi"
count={}
for ch in s:
    count[ch]=count.get(ch,0)+1

In [52]:
s = input("Enter string: ").lower()
vowels="aeiou"
count={v:0 for v in vowels}
for ch in s:
    if ch in vowels:
        count[ch]+=1
print(count)
print("Vowels present:",[v for v in vowels if count[v]>0])

Enter string:  Amulya is here

{'a': 2, 'e': 2, 'i': 1, 'o': 0, 'u': 1}
Vowels present: ['a', 'e', 'i', 'u']

In [53]:
mapping = {"0":"Zero","1":"One","2":"Two","3":"Three","4":"Four","5":"Five","6":"Six","7":"Seven","8":"Eight","9":"Nine"}
def num_to_words(n):
    return " ".join(mapping[d] for d in str(n))
print(num_to_words(452))

Four Five Two

In [54]:
s = input("Enter sentence: ").lower()
words=s.split()
freq={}
for w in words:
    freq[w]=freq.get(w,0)+1
duplicates={w:f for w,f in freq.items() if f>1}
print(duplicates)

Enter sentence:  Amulya is here

{}

In [55]:
def unique_words(sentence):
    words=sentence.lower().split()
    uniq=sorted(set(words))
    print(uniq)
unique_words("This is a test this is only a test")

['a', 'is', 'only', 'test', 'this']

### Lab-02/12/2025

In [56]:
import numpy as np
import random
g=np.array([[2,3,4],[6,7,3],[7,8,5],[55,77,66]])
print(g)

[[ 2  3  4]
 [ 6  7  3]
 [ 7  8  5]
 [55 77 66]]

In [57]:
g[0,1]

3

In [58]:
g[1]

array([6, 7, 3])

In [59]:
g[0:3]

array([[2, 3, 4],
       [6, 7, 3],
       [7, 8, 5]])

In [60]:
g[[0,3]]

array([[ 2,  3,  4],
       [55, 77, 66]])

In [61]:
g[:]

array([[ 2,  3,  4],
       [ 6,  7,  3],
       [ 7,  8,  5],
       [55, 77, 66]])

In [62]:
g[:,0]

array([ 2,  6,  7, 55])

In [63]:
g[:,1:3]

array([[ 3,  4],
       [ 7,  3],
       [ 8,  5],
       [77, 66]])

In [64]:
g[:,[1,2]]

array([[ 3,  4],
       [ 7,  3],
       [ 8,  5],
       [77, 66]])

In [67]:
import numpy as np
n=np.arange(1,6)
v=n.view()
print(n)
print(v)

[1 2 3 4 5]
[1 2 3 4 5]

In [69]:
print(id(n))
print(id(v))

136037786161392
136037786161776

In [70]:
print(n.ctypes.data)

777000640

In [71]:
print(v.ctypes.data)

777000640

In [72]:
import numpy as np
n=np.arange(1,6)
v=n.view()
n[1]*=10
print(n)
print(v)

[ 1 20  3  4  5]
[ 1 20  3  4  5]

In [73]:
import numpy as np
n=np.arange(1,6)
v=n[1:5]
print(n)
print(v)
v[1]*=10
print(n)
print(v)

[1 2 3 4 5]
[2 3 4 5]
[ 1  2 30  4  5]
[ 2 30  4  5]

In [74]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

In [78]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
a.resize((2,2))
print(a)

[1 2 3 4]
[[1 2]
 [3 4]]

In [81]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
f=g.flatten()
print(g)
print(f)

[[87 77 99]
 [22 45 76]]
[87 77 99 22 45 76]

In [82]:
f[0]=10
f

array([10, 77, 99, 22, 45, 76])

In [83]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
f=g.ravel()
print(f)

[87 77 99 22 45 76]

In [84]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
print(g.T)

[[87 22]
 [77 45]
 [99 76]]

In [85]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
g1=np.array([[55,66,77],[22,33,44]])
print(g)
print(g1)

[[87 77 99]
 [22 45 76]]
[[55 66 77]
 [22 33 44]]

In [87]:
print(np.hstack((g,g1)))

[[87 77 99 55 66 77]
 [22 45 76 22 33 44]]

In [88]:
print(np.vstack((g,g1)))

[[87 77 99]
 [22 45 76]
 [55 66 77]
 [22 33 44]]

In [89]:
import pandas as pd
import numpy as np
obj=pd.Series([87,100,94])
obj

0     87
1    100
2     94
dtype: int64

In [91]:
print(obj[0])

98

In [90]:
import pandas as pd
obj=pd.Series(98,range(3))
obj

0    98
1    98
2    98
dtype: int64

In [96]:
import pandas as pd
import numpy as np
obj=pd.Series([87,100,94])
obj

0     87
1    100
2     94
dtype: int64

In [98]:
print(obj.count())
print(obj.mean())
print(obj.min())
print(obj.max())
print(obj.std())

3
93.66666666666667
87
100
6.506407098647712

In [99]:
print(obj.describe())

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [101]:
# 50% represents the median of sorted value
# 25% represents median of first half of the sorted value- is the avg of 87 and 94
# 75% represents median of the second half of the sorted value- is the avg of 94 and 100
# Together the inter quartile range is 75% Quartile - the 25% Quartile while is the measure of disperssion

In [102]:
import pandas as pd
import numpy as np
grades=pd.Series([87,100,94],index=[1,2,3])
grades

1     87
2    100
3     94
dtype: int64

In [103]:
grades=pd.Series({'Wally':84,'Eva':100,'Sam':94})
grades

Wally     84
Eva      100
Sam       94
dtype: int64

In [104]:
grades['Eva']

100

In [105]:
grades.Wally

84

In [107]:
grades.dtype

dtype('int64')

In [108]:
grades.values

array([ 84, 100,  94])

In [109]:
hardware=pd.Series(['Hammar','Saw','Wrench'])
hardware

0    Hammar
1       Saw
2    Wrench
dtype: object

In [112]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [113]:
hardware.str.upper()

0    HAMMAR
1       SAW
2    WRENCH
dtype: object

In [114]:
import pandas as pd
grades_dict={'Wally':[87,96,70],'Eva':[100,87,90],'Sam':[94,77,90],'Katie':[100,81,82],'Bob':[83,65,85]}
grades=pd.DataFrame(grades_dict)
grades

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [115]:
grades.index=['Test1','Test2','Test3']
grades

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [116]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [117]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [118]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [119]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [120]:
grades.loc['Test1':'Test3']

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [124]:
grades.iloc[0:2]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [125]:
grades.loc[['Test1','Test3']]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [126]:
grades.iloc[[0,2]]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85