In [1]:
x=int(input('Enter the number: '))
exp=x**3+2*x**2+3*x+4
print(exp)

Enter the number:  5

194

In [2]:
import math
r=float(input("Enter the radius: "))
area=math.pi*r*r
volume=4*math.pi*r*r*r/3
print("Area: ",area)
print('Volume: ',volume)

Enter the radius:  5

Area:  78.53981633974483
Volume:  523.5987755982989

In [3]:
a=1.21
b=1.20
c=1.22
check=(a<b) or (not(c==b)) and (c<a)
print (check)

False

In [4]:
n=int(input("Enter the time: "))
p=1000
r=0.12
a=p*(1+r)**n
print("The amount is",a)

Enter the time:  15

The amount is 5473.565759257045

In [5]:
import math
a=math.pow(math.e,math.pi)
b=math.pow(math.pi,math.e)
if a>b:
    print("Ok")
else:
    print("Ok Anyway")

Ok

In [6]:
a=-7*20+8/16*2+54
b=7**2//9%3
c=(7-4*2)*10-25*8//5
d=5%10+10-25*8//5
print(a,b,c,d)

-85.0 2 -50 -25

In [7]:
cost_meal=float(input("Enter the cost of the meal: "))
tip=0.18*cost_meal
tax=0.05*cost_meal
grand_total=cost_meal+tax+tip
print(f"The cost was: {cost_meal:.2f}")
print(f"The tax was: {tax:.2f}")
print(f"The tip was: {tip:.2f}")
print(f"The Grand Total was: {grand_total:.2f}")

Enter the cost of the meal:  156

The cost was: 156.00
The tax was: 7.80
The tip was: 28.08
The Grand Total was: 191.88

In [8]:
a=int(input("Enter num1: "))
b=int(input("Enter num2: "))
print("The sum is: ",(a+b))
print("The difference is: ",(a-b))
print("The product is: ",(a*b))
print("The quotient is: ",(a/b))
print("The remainder is: ",(a%b))
print("The Log Result: ",(math.log10(5)))
print("The result is: ",a+b)

Enter num1:  15
Enter num2:  16

The sum is:  31
The difference is:  -1
The product is:  240
The quotient is:  0.9375
The remainder is:  15
The Log Result:  0.6989700043360189
The result is:  31

In [9]:
d=float(input("Enter the height: "))
vi,a=0,9.8
vf=math.sqrt(math.pow(vi,2)+(2*a*d))
print("The final velocity is: ",vf)

Enter the height:  5.5

The final velocity is:  10.382677881933928

In [10]:
cel=float(input("Enter degree cel: "))
fah=(cel*9/5)+32
kel=cel++273.15
print(f"Temp in Fahrenheit: {fah:.2f}F")
print(f"Temp in Kelvin: {fah:.2f}K")

Enter degree cel:  9.5

Temp in Fahrenheit: 49.10F
Temp in Kelvin: 49.10K

In [11]:
num=int(input("Enter a 4 digit integer: "))
dig1=num//1000
dig2=(num//100)%10
dig3=(num//10)%10
dig4=num%10
sum1=dig1+dig2+dig3+dig4
print("The sum is: ",sum1)

Enter a 4 digit integer:  4567

The sum is:  22

In [12]:
num1=int(input())
num2=int(input())
num3=int(input())
min1=min(num1,num2,num3)
max1=max(num1,num2,num3)
mid1=(num1+num2+num3)-min1-max1
print(min1,max1,mid1)

 1
 2
 3

1 3 2

In [13]:
days=int(input("Enter Days: "))
hour=int(input("Enter Hours: "))
minutes=int(input("Enter Minutes: "))
seconds=int(input("Enter Seconds: "))
total=days*24*60*60+hour*60*60+minutes*60+seconds
print(total," Value")

Enter Days:  365
Enter Hours:  24
Enter Minutes:  24
Enter Seconds:  5

31623845  Value

In [14]:
answer=input("Is it raining?: ")
if answer=="Yes":
    print("Carry an umbrella")
else:
    print("Bye")

Is it raining?:  Yes

Carry an umbrella

In [15]:
# try:
#     answer = input("Is it raining?: ")
#     match answer:
#         case "Yes":
#             print("Carry an umbrella.")
#         case "No":
#             print("Bye")
#         case _:
#             print("Don't carry anything")
# except ValueError:
#     print("Error Input")

In [16]:
answer=input("Is it raining?: ")
if answer=="Yes":
    print("Carry an umbrella")
elif answer=="No":
    print("Bye")
else:
    print("Don't carry anything")

Is it raining?:  Yes

Carry an umbrella

In [17]:
marks=int(input("Enter the marks: "))
if marks>=90 and marks<=100:
    print("Excellent: A")
elif marks>=80 and marks<90:
    print("Good: B")
elif marks>=70 and marks<80:
    print("Average: C")
elif marks>=60 and marks<70:
    print("Needs Imporovement: D")
else:
    print("Failing: F")

Enter the marks:  98

Excellent: A

In [18]:
side1=int(input("Enter the side1: "))
side2=int(input("Enter the side2: "))
side3=int(input("Enter the side3: "))
if side1==side2==side3:
    print("Equilateral Triangle")
elif side1==side2 or side2==side3 or side==side3:
    print("Isosceles Triangle")
else:
    print("Scalene Triangle")

Enter the side1:  15
Enter the side2:  15
Enter the side3:  25

Isosceles Triangle

In [19]:
if int(input("Enter a number: "))%2==0:
    print("The number is even")
else:
    print("The number is odd")

Enter a number:  15

The number is odd

In [20]:
year=int(input("Enter the year: "))
if year%100==0 or year%4==0:
    print("The year is leap")
else:
    print("It's not a leap year")

Enter the year:  2020

The year is leap

In [21]:
prime=int(input('Enter a number: '))
def primes(prime):
    if prime<=1:
        return False
    for i in range(2,math.sqrt(prime)+1):
        if prime%i==0:
            return False
        else:
            return True
print()

Enter a number:  5

### Lab-25/11/2025

In [22]:
colors={'red','orange','yellow','green','red','blue'}
colors

{'blue', 'green', 'orange', 'red', 'yellow'}

In [23]:
len(colors)

5

In [24]:
'red' in colors

True

In [25]:
'purple' in colors

False

In [26]:
'purple' not in colors

True

In [27]:
for color in colors:
    print(color.upper(),end=' ')

YELLOW GREEN RED BLUE ORANGE

In [28]:
numbers=list(range(10))+list(range(5))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]

In [29]:
set(numbers)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [30]:
set()

set()

In [31]:
text='to be or not be that id the question'
unique_words=set(text.split())
for word in sorted(unique_words):
    print(word,end=" ")

be id not or question that the to

In [32]:
{1,3,5}=={3,5,1}

True

In [33]:
{1,3,5}!={3,5,1}

False

In [34]:
{1,3,5}<{3,5,1}

False

In [35]:
{1,3,5}<{7,3,5,1}

True

In [36]:
{1,3,5}<={3,5,1}

True

In [37]:
{1,3}<={3,5,1}

True

In [38]:
{1,3,5}.issubset({3,5,1})

True

In [39]:
{1,3,5}.issubset({3,5,1})

True

In [40]:
{1,3,5}>{3,5,1}

False

In [41]:
{1,3,5,7}>{3,5,1}

True

In [42]:
students={}
name=input("Enter student name: ")
marks=int(input("Enter marks: "))
students[name]=marks
search=input("Enter name to display marks: ")
print(students.get(search,"Student not found"))

Enter student name:  Amulya
Enter marks:  98
Enter name to display marks:  Deep

Student not found

In [43]:
data={}
for i in range(3):
    name=input("Enter name: ")
    percent=float(input("Enter percentage: "))
    data[name]=percent
print(data)

Enter name:  Amulya
Enter percentage:  98
Enter name:  Deep
Enter percentage:  85
Enter name:  Shrivastava
Enter percentage:  85

{'Amulya': 98.0, 'Deep': 85.0, 'Shrivastava': 85.0}

In [45]:
d=eval(input("Enter dictionary: "))
print(sum(d.values()))

Enter dictionary:  {'A':95,'B':65}

160

In [46]:
e2f={"dog":"chien","cat":"chat","walrus":"morse"}
print(e2f)

{'dog': 'chien', 'cat': 'chat', 'walrus': 'morse'}

In [47]:
tlds={"Canada":"ca","United States":"us","Mexico":"mx"}
a="Canada" in tlds
b="France" in tlds
pairs=[(k,v) for k,v in tlds.items()]
tlds["Sweden"]="sw"
tlds["Sweden"]="se"
rev={v:k for k,v in tlds.items()}

In [48]:
roman = {"I":1,"II":2,"III":3,"V":5}
keys=list(roman.keys())
values=list(roman.values())
items=list(roman.items())

In [49]:
cubes={x:x**3 for x in range(1, 6)}

In [50]:
life = {"animals":{"cats": ["Henri", "Grumpy", "Lucy"],"octopi":{},"emus":{}},"plants":{},"other":{}}

In [51]:
s="mississippi"
count={}
for ch in s:
    count[ch]=count.get(ch,0)+1

In [52]:
s = input("Enter string: ").lower()
vowels="aeiou"
count={v:0 for v in vowels}
for ch in s:
    if ch in vowels:
        count[ch]+=1
print(count)
print("Vowels present:",[v for v in vowels if count[v]>0])

Enter string:  MOM

{'a': 0, 'e': 0, 'i': 0, 'o': 1, 'u': 0}
Vowels present: ['o']

In [53]:
mapping = {"0":"Zero","1":"One","2":"Two","3":"Three","4":"Four","5":"Five","6":"Six","7":"Seven","8":"Eight","9":"Nine"}
def num_to_words(n):
    return " ".join(mapping[d] for d in str(n))
print(num_to_words(452))

Four Five Two

In [54]:
s = input("Enter sentence: ").lower()
words=s.split()
freq={}
for w in words:
    freq[w]=freq.get(w,0)+1
duplicates={w:f for w,f in freq.items() if f>1}
print(duplicates)

Enter sentence:  Amulya is here

{}

In [55]:
def unique_words(sentence):
    words=sentence.lower().split()
    uniq=sorted(set(words))
    print(uniq)
unique_words("This is a test this is only a test")

['a', 'is', 'only', 'test', 'this']

### Lab-02/12/2025

In [56]:
import numpy as np
import random
g=np.array([[2,3,4],[6,7,3],[7,8,5],[55,77,66]])
print(g)

[[ 2  3  4]
 [ 6  7  3]
 [ 7  8  5]
 [55 77 66]]

In [57]:
g[0,1]

3

In [58]:
g[1]

array([6, 7, 3])

In [60]:
g[0:3]

array([[2, 3, 4],
       [6, 7, 3],
       [7, 8, 5]])

In [61]:
g[[0,3]]

array([[ 2,  3,  4],
       [55, 77, 66]])

In [62]:
g[:]

array([[ 2,  3,  4],
       [ 6,  7,  3],
       [ 7,  8,  5],
       [55, 77, 66]])

In [63]:
g[:,0]

array([ 2,  6,  7, 55])

In [64]:
g[:,1:3]

array([[ 3,  4],
       [ 7,  3],
       [ 8,  5],
       [77, 66]])

In [65]:
g[:,[1,2]]

array([[ 3,  4],
       [ 7,  3],
       [ 8,  5],
       [77, 66]])

In [66]:
import numpy as np
n=np.arange(1,6)
v=n.view()
print(n)
print(v)

[1 2 3 4 5]
[1 2 3 4 5]

In [67]:
print(id(n))
print(id(v))

124908099704272
124908099706192

In [68]:
print(n.ctypes.data)

282564816

In [69]:
print(v.ctypes.data)

282564816

In [70]:
import numpy as np
n=np.arange(1,6)
v=n.view()
n[1]*=10
print(n)
print(v)

[ 1 20  3  4  5]
[ 1 20  3  4  5]

In [71]:
import numpy as np
n=np.arange(1,6)
v=n[1:5]
print(n)
print(v)
v[1]*=10
print(n)
print(v)

[1 2 3 4 5]
[2 3 4 5]
[ 1  2 30  4  5]
[ 2 30  4  5]

In [72]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

In [73]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
a.resize((2,2))
print(a)

[1 2 3 4]
[[1 2]
 [3 4]]

In [74]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
f=g.flatten()
print(g)
print(f)

[[87 77 99]
 [22 45 76]]
[87 77 99 22 45 76]

In [75]:
f[0]=10
f

array([10, 77, 99, 22, 45, 76])

In [76]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
f=g.ravel()
print(f)

[87 77 99 22 45 76]

In [77]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
print(g.T)

[[87 22]
 [77 45]
 [99 76]]

In [78]:
import numpy as np
g=np.array([[87,77,99],[22,45,76]])
g1=np.array([[55,66,77],[22,33,44]])
print(g)
print(g1)

[[87 77 99]
 [22 45 76]]
[[55 66 77]
 [22 33 44]]

In [79]:
print(np.hstack((g,g1)))

[[87 77 99 55 66 77]
 [22 45 76 22 33 44]]

In [80]:
print(np.vstack((g,g1)))

[[87 77 99]
 [22 45 76]
 [55 66 77]
 [22 33 44]]

In [81]:
import pandas as pd
import numpy as np
obj=pd.Series([87,100,94])
obj

0     87
1    100
2     94
dtype: int64

In [82]:
print(obj[0])

87

In [83]:
import pandas as pd
obj=pd.Series(98,range(3))
obj

0    98
1    98
2    98
dtype: int64

In [84]:
import pandas as pd
import numpy as np
obj=pd.Series([87,100,94])
obj

0     87
1    100
2     94
dtype: int64

In [85]:
print(obj.count())
print(obj.mean())
print(obj.min())
print(obj.max())
print(obj.std())

3
93.66666666666667
87
100
6.506407098647712

In [86]:
print(obj.describe())

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [87]:
# 50% represents the median of sorted value
# 25% represents median of first half of the sorted value- is the avg of 87 and 94
# 75% represents median of the second half of the sorted value- is the avg of 94 and 100
# Together the inter quartile range is 75% Quartile - the 25% Quartile while is the measure of disperssion

In [88]:
import pandas as pd
import numpy as np
grades=pd.Series([87,100,94],index=[1,2,3])
grades

1     87
2    100
3     94
dtype: int64

In [89]:
grades=pd.Series({'Wally':84,'Eva':100,'Sam':94})
grades

Wally     84
Eva      100
Sam       94
dtype: int64

In [90]:
grades['Eva']

100

In [91]:
grades.Wally

84

In [92]:
grades.dtype

dtype('int64')

In [93]:
grades.values

array([ 84, 100,  94])

In [94]:
hardware=pd.Series(['Hammar','Saw','Wrench'])
hardware

0    Hammar
1       Saw
2    Wrench
dtype: object

In [95]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [96]:
hardware.str.upper()

0    HAMMAR
1       SAW
2    WRENCH
dtype: object

In [97]:
import pandas as pd
grades_dict={'Wally':[87,96,70],'Eva':[100,87,90],'Sam':[94,77,90],'Katie':[100,81,82],'Bob':[83,65,85]}
grades=pd.DataFrame(grades_dict)
grades

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [98]:
grades.index=['Test1','Test2','Test3']
grades

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [99]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [100]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [101]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [102]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [103]:
grades.loc['Test1':'Test3']

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [104]:
grades.iloc[0:2]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [105]:
grades.loc[['Test1','Test3']]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [106]:
grades.iloc[[0,2]]

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

### Lab-09_12_2025

In [107]:
s='   this is a test string\t\t'
print(s.lstrip())

this is a test string

In [108]:
'Happy Birthday'.capitalize()

'Happy birthday'

In [109]:
'Happy Birthday'.title()

'Happy Birthday'

In [110]:
print(f"A:{ord('A')} a:{ord('a')}")

A:65 a:97

In [111]:
"Orange"<"orange"

True

In [112]:
"Orange"<="orange"

True

In [113]:
s='to be or not to be'
s.count('to')

2

In [114]:
s='to be or not to be'
s.count('to',0,12)

1

In [115]:
s='to be or not to be'
s.rindex('to')

13

In [116]:
ss='to be or not to be'
s.rfind('to')

13

In [ ]:
s="to be or not to be"
"to" in s

In [117]:
s="to be or not to be"
s.endswith('be')

True

In [118]:
s="A,B,C,D"
s.replace(",","->")

'A->B->C->D'

In [119]:
s='A,B,C,D'
s.split(',')

['A', 'B', 'C', 'D']

In [120]:
s='A,B,C,D'
s.split(',',2)

['A', 'B', 'C,D']

In [121]:
s='A,B,C,D'
'->'.join(s)

'A->,->B->,->C->,->D'

In [122]:
"-".join([str(i) for i in range(10)])

'0-1-2-3-4-5-6-7-8-9'

In [123]:
'Ram:89,97,99'.partition(':')

('Ram', ':', '89,97,99')

In [124]:
'Ram:89,97,99'.rpartition(':')

('Ram', ':', '89,97,99')

In [125]:
l='''this is 1st line
this is 2nd line
this is 3rd line'''
l.splitlines()

['this is 1st line', 'this is 2nd line', 'this is 3rd line']

In [126]:
'-27'.isdigit()

False

In [127]:
'A27 is not a number'.isalnum()

False

In [128]:
s=r'hello\nworld'
print(s)

hello\nworld

### Assignment-06

In [129]:
import numpy as np
A = np.arange(4).reshape(2,2)
print("A:\n", A)
cube = A**3
print("\nCube:\n", cube)
add7 = A + 7
print("\nAdd 7:\n", add7)
mul2 = A * 2
print("\nMultiply by 2:\n", mul2)

A:
 [[0 1]
 [2 3]]

Cube:
 [[ 0  1]
 [ 8 27]]

Add 7:
 [[ 7  8]
 [ 9 10]]

Multiply by 2:
 [[0 2]
 [4 6]]

In [130]:
A = np.arange(2, 20, 2).reshape(3,3)
B = np.arange(9, 0, -1).reshape(3,3)
C = A * B
print(C)

[[18 32 42]
 [48 50 48]
 [42 32 18]]

In [131]:
M = np.arange(1,13).reshape(3,4)
print("Original:\n", M)
M2 = M[[1,0,2]]   
M3 = M2[:, [2,1,0,3]]
print("\nModified:\n", M3)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Modified:
 [[ 7  6  5  8]
 [ 3  2  1  4]
 [11 10  9 12]]

In [132]:
L1 = [2,3,5,7,11]
L2 = [13,17,19,23,29]
A = np.array([L1, L2])
print(A)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]

In [133]:
A = 2**np.arange(6).reshape(2,3)
print("Original:\n", A)
flat1 = A.flatten(order='C')
flat2 = A.ravel(order='C')
print("\nFlatten:", flat1)
print("Ravel:", flat2)
print("\nOriginal unchanged:\n", A)

Original:
 [[ 1  2  4]
 [ 8 16 32]]

Flatten: [ 1  2  4  8 16 32]
Ravel: [ 1  2  4  8 16 32]

Original unchanged:
 [[ 1  2  4]
 [ 8 16 32]]

In [134]:
arr = np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,0,2,6])
vals, counts = np.unique(arr, return_counts=True)
most = vals[counts == counts.max()]
print("Most frequent value(s):", most)

Most frequent value(s): [5]

In [135]:
A = np.linspace(1.1, 6.6, 6).reshape(2,3)
print("A:\n", A)
ints = A.astype(int)
print("\nAs int:\n", ints)

A:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]]

As int:
 [[1 2 3]
 [4 5 6]]

In [136]:
def format_2d_array(arr):
    max_width = max(len(str(x)) for row in arr for x in row)
    lines = []
    for row in arr:
        formatted = " ".join(f"{str(x).rjust(max_width)}" for x in row)
        lines.append(formatted)
    return "\n".join(lines)
M = [[1,200,3],[40,5,600]]
print(format_2d_array(M))

  1 200   3
 40   5 600

In [137]:
A = np.arange(1,16).reshape(3,5)
print("A:\n", A)
print("\nRow 2:\n", A[1])
print("\nColumn 5:\n", A[:,4])
print("\nRows 0 & 1:\n", A[0:2])
print("\nColumns 2–4:\n", A[:,1:4])
print("\nElement (1,4):", A[1,3])
print("\nRows 1–2, Cols 0,2,4:\n", A[1:3][:, [0,2,4]])

A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Row 2:
 [ 6  7  8  9 10]

Column 5:
 [ 5 10 15]

Rows 0 & 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Columns 2–4:
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

Element (1,4): 9

Rows 1–2, Cols 0,2,4:
 [[ 6  8 10]
 [11 13 15]]

In [138]:
array1 = np.array([[1,2],[2,3]])
array2 = np.array([[4,5],[6,7]])
print(array1 + array2)
print(array1 * array2)
print(array1 @ array2)
print(np.concatenate((array1, array2), axis=0))
print(np.concatenate((array1, array2), axis=1))

[[ 5  7]
 [ 8 10]]
[[ 4 10]
 [12 21]]
[[16 19]
 [26 31]]
[[1 2]
 [2 3]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [2 3 6 7]]

In [139]:
import numpy as np
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])
array3 = np.vstack((array1,array2))
array4 = np.hstack((array1,array2))
array5 = np.vstack((array2,array2))
array6 = np.hstack((array2,array2))
print("array3:\n", array3)
print("array4:\n", array4)
print("array5:\n", array5)
print("array6:\n", array6)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4:
 [[0 1 4 5]
 [2 3 6 7]]
array5:
 [[4 5]
 [6 7]
 [4 5]
 [6 7]]
array6:
 [[4 5 4 5]
 [6 7 6 7]]

In [140]:
array3c = np.concatenate((array1,array2),axis=0)
array4c = np.concatenate((array1,array2),axis=1)
array5c = np.concatenate((array2,array2),axis=0)
array6c = np.concatenate((array2,array2),axis=1)
print("array3c:\n", array3c)
print("array4c:\n", array4c)
print("array5c:\n", array5c)
print("array6c:\n", array6c)

array3c:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4c:
 [[0 1 4 5]
 [2 3 6 7]]
array5c:
 [[4 5]
 [6 7]
 [4 5]
 [6 7]]
array6c:
 [[4 5 4 5]
 [6 7 6 7]]

In [141]:
checker = np.zeros((8,8),dtype=int)
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print("checker:\n", checker)

checker:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

In [142]:
board = np.full((8,8),'-',dtype=str)
board[1::2,::2] = '*'
board[::2,1::2] = '*'
print("board:\n", board)

board:
 [['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]

In [143]:
rand5 = np.random.randint(0,10,(5,5))
u,c = np.unique(rand5,return_counts=True)
count_dict = dict(zip(u,c))
print("rand5:\n", rand5)
print("count_dict:", count_dict)

rand5:
 [[9 3 6 4 7]
 [0 8 1 0 7]
 [3 7 6 6 1]
 [9 7 9 2 7]
 [0 4 1 6 9]]
count_dict: {0: 3, 1: 3, 2: 1, 3: 2, 4: 2, 6: 4, 7: 5, 8: 1, 9: 4}

In [144]:
def stats(x):
    a = np.ravel(x)
    mean = np.sum(a)/len(a)
    s = np.sort(a)
    n = len(a)
    median = s[n//2] if n%2==1 else (s[n//2-1]+s[n//2])/2
    v,t = np.unique(a,return_counts=True)
    mode = v[np.argmax(t)]
    return mean,median,mode
A7 = np.random.randint(0,20,(4,4))
B7 = np.random.randint(0,20,(2,8))
C7 = np.random.randint(0,20,(1,12))
print("A7:\n", A7)
print("statsA:", stats(A7))
print("B7:\n", B7)
print("statsB:", stats(B7))
print("C7:\n", C7)
print("statsC:", stats(C7))

A7:
 [[19  8 15  3]
 [ 3  8  9 16]
 [16 17  3 17]
 [ 5  0 18  2]]
statsA: (9.9375, 8.5, 3)
B7:
 [[ 5 17  1 13  4  5  9  4]
 [ 6 17  3  1 19  6 12  7]]
statsB: (8.0625, 6.0, 1)
C7:
 [[10  3 10  8  3 13  7  9  7 17 16  1]]
statsC: (8.666666666666666, 8.5, 3)

In [145]:
M99 = np.random.rand(99,2)
sample5 = M99[:5]
print("sample5:\n", sample5)

sample5:
 [[0.77809755 0.95591122]
 [0.99924706 0.81797855]
 [0.03299058 0.27820983]
 [0.65262014 0.83506807]
 [0.50967183 0.5468887 ]]

In [146]:
A44 = np.random.rand(44,4)
sortedA44 = np.sort(A44,axis=0)
print("sortedA44:\n", sortedA44)

sortedA44:
 [[0.00410632 0.00177871 0.10658528 0.0559166 ]
 [0.03681783 0.01001524 0.1201498  0.07214463]
 [0.04057861 0.02626915 0.12212605 0.10906404]
 [0.05410958 0.07701482 0.13325863 0.20701707]
 [0.05930288 0.08730797 0.14297847 0.23938365]
 [0.09061104 0.11025057 0.16888475 0.26220103]
 [0.13571638 0.11644196 0.19037447 0.26677693]
 [0.16624545 0.15878319 0.21243605 0.28852635]
 [0.1726879  0.20996574 0.21288893 0.29841705]
 [0.17655582 0.2203425  0.21495783 0.31384863]
 [0.21326292 0.23702459 0.24834617 0.31431763]
 [0.22910584 0.26331429 0.25989601 0.33278738]
 [0.2592321  0.31708759 0.28024082 0.34072527]
 [0.30279597 0.33239616 0.3002912  0.35163364]
 [0.31881657 0.37455869 0.31617947 0.35713776]
 [0.32143864 0.4110997  0.34336466 0.36810334]
 [0.38169776 0.4214937  0.34703902 0.39042314]
 [0.38623632 0.44351424 0.37658052 0.40283577]
 [0.40479403 0.44677447 0.3865545  0.41367581]
 [0.42488932 0.44734278 0.39316575 0.42282082]
 [0.52817675 0.45639848 0.40008544 0.46192336]
 [0.55290542 0.52588655 0.41536551 0.46324817]
 [0.57585932 0.54269089 0.42924787 0.48507623]
 [0.5788286  0.55462361 0.46252663 0.50759553]
 [0.57984781 0.56245027 0.4670766  0.52710249]
 [0.59609575 0.58155223 0.48401043 0.57649396]
 [0.59988697 0.58285558 0.50731429 0.60628091]
 [0.61879188 0.60598246 0.5285519  0.64437844]
 [0.61904595 0.62598679 0.54465221 0.64654641]
 [0.65735354 0.64582646 0.55779176 0.64690216]
 [0.69570829 0.65176259 0.55850519 0.6509197 ]
 [0.70908617 0.65559837 0.60472489 0.68016889]
 [0.72516122 0.74632321 0.62081805 0.68378159]
 [0.76270448 0.76095808 0.62478058 0.69872698]
 [0.77192282 0.79421815 0.62727145 0.7259328 ]
 [0.79610227 0.82430638 0.65247924 0.72733575]
 [0.80554179 0.86387026 0.66331503 0.73427674]
 [0.81889793 0.88038615 0.7609451  0.74758099]
 [0.83361476 0.91806143 0.88319342 0.7790018 ]
 [0.84613615 0.93027394 0.89761971 0.88165923]
 [0.89357303 0.96994273 0.90206783 0.89113759]
 [0.92404437 0.97327012 0.93906059 0.90008037]
 [0.93338631 0.97824254 0.94906994 0.98205839]
 [0.96719043 0.99514794 0.99984642 0.99952326]]

In [147]:
import pandas as pd
df = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
seriesA = df['A']
print("seriesA:\n", seriesA)

seriesA:
 0    1
1    2
2    3
3    4
Name: A, dtype: int64

In [148]:
S1 = pd.Series([1,2,3,4])
S2 = pd.Series([3,4,5,6])
not_in_S2 = S1[~S1.isin(S2)]
print("not_in_S2:\n", not_in_S2)

not_in_S2:
 0    1
1    2
dtype: int64

In [149]:
s_find = pd.Series([1,1,3,7.88,12,88,23,3,1,9])
min_idx = s_find.idxmin()
max_idx = s_find.idxmax()
print("min_idx:", min_idx)
print("max_idx:", max_idx)

min_idx: 0
max_idx: 5

In [150]:
L = ['Carpet','Orange','Sky','Banana']
sL = pd.Series(L)
vowels = sL[sL.str[0].str.lower().isin(['a','e','i','o','u'])]
print("vowels:\n", vowels)

vowels:
 1    Orange
dtype: object

In [151]:
vowel_series = vowels
print("vowel_series:\n", vowel_series)

vowel_series:
 1    Orange
dtype: object